AMPL_path: null
all_data: {}
ampl_options:
  _log_input_only: false
  gurobi_options: predual=-1 method=2 crossover=0 prepasses=3 barconvtol=1e-6 presolve=-1
  log_file: output/log.txt
  presolve: 10
  presolve_eps: 1e-7
  presolve_fixeps: 1e-7
  show_boundtol: 0
  show_stats: 3
  solver: gurobi
case_study: GWP_tot_min_corr
cost_limit: 80000
cs_path: case_studies
data_dir: C:/Users/reynt/LMECA2675/EnergyScope-EnergyScope.py/Data/2050
es_path: C:/Users/reynt/LMECA2675/EnergyScope-EnergyScope.py/energyscope/energy_model
gwp_min: 4000
lim_gwp_op: 1000
nbr_td: 12
print_hourly_data: true
print_sankey: true
printing: true
printing_td: true
step1_path: energyscope/preprocessing/td_selection
